from universe import NASDAQ_100_TEST_UNIVERSE


DEFAULT_TICKER = "AAPL"
DATA_PERIOD = "2y"

SHORT_MOMENTUM_DAYS = 5
LONG_MOMENTUM_DAYS = 20
MOVING_AVERAGE_DAYS = 20

STOCK_UNIVERSE = NASDAQ_100_TEST_UNIVERSE
SCANNER_RESULT_LIMIT = 20
